# Generated by Django 2.1.2 on 2018-11-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv_name', models.CharField(default='', max_length=100, verbose_name='收货人')),
                ('recv_tel', models.CharField(default='', max_length=20, verbose_name='收货人的电话号码')),
                ('province', models.CharField(default='', max_length=100, verbose_name='收货人的省份')),
                ('city', models.CharField(default='', max_length=100, verbose_name='收货人的城市')),
                ('area', models.CharField(default='', max_length=100, verbose_name='收货人的县区')),
                ('street', models.CharField(default='', max_length=255, verbose_name='收货人的街道')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否是默认地址')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('areaid', models.CharField(max_length=50, verbose_name='区域ID')),
                ('area', models.CharField(default='', max_length=50, verbose_name='区域')),
                ('cityid', models.CharField(max_length=50, verbose_name='城市ID')),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityid', models.CharField(max_length=50, verbose_name='城市ID')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('provinceid', models.CharField(max_length=50, verbose_name='省份ID')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=20, verbose_name='用户名称')),
                ('password', models.CharField(max_length=40, verbose_name='用户密码')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('tel', models.IntegerField(verbose_name='电话')),
                ('avatar', models.ImageField(default='', upload_to='static/img/users/', verbose_name='用户头像')),
                ('is_active', models.BooleanField(default=False, verbose_name='激活状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_manager', models.BooleanField(default=False, verbose_name='管理员')),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provinceid', models.CharField(max_length=50, verbose_name='省份ID')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Passport', verbose_name='账户'),
        ),
    ]
