# Generated by Django 2.0 on 2018-11-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
    ]
