# Generated by Django 2.1.2 on 2018-10-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='static/article/img/default.gif', upload_to='static/article/img/', verbose_name='用户头像'),
        ),
    ]
