# Generated by Django 2.1.2 on 2018-11-02 11:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20181030_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='文章内容'),
        ),
    ]
