# Generated by Django 2.1.2 on 2018-11-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False, verbose_name='禁用评论')),
                ('content', models.CharField(max_length=1000, verbose_name='评论内容')),
                ('title', models.CharField(default='', max_length=20, verbose_name='评论标题')),
                ('rating', models.IntegerField(default=1, verbose_name='评分')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Passport', verbose_name='用户')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
