# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章主键')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('remark', models.CharField(default='', max_length=255, verbose_name='文章摘要')),
                ('publishTime', models.DateTimeField(auto_now_add=True, verbose_name='文章发表时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='文章修改时间')),
                ('count', models.IntegerField(default=0, verbose_name='文章点击量')),
            ],
            options={
                'ordering': ['-publishTime'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户主键')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名称')),
                ('password', models.CharField(max_length=255, verbose_name='用户密码')),
                ('nickname', models.CharField(default='普通用户', max_length=255, verbose_name='用户昵称')),
                ('age', models.IntegerField(default=18, verbose_name='用户年龄')),
                ('gender', models.CharField(default='女', max_length=10, verbose_name='用户性别')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户邮箱')),
                ('avatar', models.ImageField(default='static/headers/default.jpg', upload_to='static/headers/', verbose_name='用户头像')),
                ('tel', models.CharField(default='110', max_length=50, verbose_name='用户头像')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
