# Generated by Django 2.1.2 on 2018-10-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章id')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('publishTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('nickname', models.CharField(default='普通用户', max_length=255, verbose_name='用户昵称')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('gender', models.CharField(default='女', max_length=10, verbose_name='性别')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hab.User'),
        ),
    ]
