# Generated by Django 2.1.2 on 2018-11-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(verbose_name='商品数量')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='商品添加时间')),
                ('allTotal', models.FloatField(verbose_name='商品小计金额')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='购物车商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Passport', verbose_name='购物车所属用户')),
            ],
        ),
    ]
