# Generated by Django 2.0 on 2018-11-14 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCar', '0002_auto_20181114_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books', verbose_name='购物车商品'),
        ),
    ]
